AWSTemplateFormatVersion: 2010-09-09
Description: This template creates an EC2 instance for compute requirements.

Parameters:
  InstanceSecurityGroup:
    Type: String
    Description: Security group of the web server, for allowing and restricting network traffic
  PublicSubnet:
    Type: String
    Description: Subnet Id of the server
  InstanceType:
    Type: String
    Description: Type of EC2 instance
  DiskSize:
    Description: EC2 Selected Disk Size
    Type: String
    Default: 40
  WebServerIamInstanceProfile:
    Description: IAM Instance Profile to access SSM service
    Type: String

Mappings:
  AWSInstanceType2Arch:
    t3.micro:
      Arch: HVM64
    t3.small:
      Arch: HVM64
    t3.medium:
      Arch: HVM64

  AWSRegionArch2AMI:
    ap-south-1:
      HVM64: ami-003873912100f1f6f

Resources:
  WebServerKeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: WebServerKey
      PublicKeyMaterial: <PUBLIC_KEY>

  WebServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId:
        !FindInMap [
          AWSRegionArch2AMI,
          !Ref "AWS::Region",
          !FindInMap [AWSInstanceType2Arch, !Ref InstanceType, Arch],
        ]
      InstanceType: !Ref InstanceType
      KeyName: !Ref WebServerKeyPair
      #SubnetId: !Ref PublicSubnet ## DONOT SPECIFY WHEN SPECIFIED AT NETWORK INTERFACE
      #SecurityGroupIds: ## SAME AS SUBNET ABOVE
      #- !Ref InstanceSecurityGroup
      BlockDeviceMappings:
        - DeviceName: "/dev/sda1"
          Ebs:
            DeleteOnTermination: "true"
            VolumeSize: !Ref DiskSize
            VolumeType: gp2
      Monitoring: "false"
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          GroupSet:
            - !Ref InstanceSecurityGroup
          SubnetId: !Ref PublicSubnet
      Tenancy: default
      IamInstanceProfile: !Ref WebServerIamInstanceProfile
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          apt update -y
          apt install -y nginx
          systemctl start nginx
          systemctl enable nginx
          echo "<h1>Hello from CloudFormation!</h1>" > /var/www/html/index.html

Outputs:
  WebServerInstancePublicDNSName:
    Description: "Public DNS of Web Server Instance"
    Value: !GetAtt WebServerInstance.PublicDnsName
    Export:
      Name: "WebServerInstancePublicDNS"
